### ISSUE TITLE
Protos: PyRO API not usable anymore

### ISSUE THREAD

**Issue by eurydice76** [ISISNeutronMuon/MDANSE#110]
When porting MDANSE to python 3, I experienced a serious problem with the parallelization of the code. Indeed, to run jobs on multiprocessor machines, MDANSE uses a wrapper written by Konrad Hinsen on top of the PyRO library. This wrapper and its corresponding library are probably one of the most difficult python codes I had the opportunity to read ... The wrapper works for PyRO version up to 3.16 the last version available on python 2. On python 3, there is now the PyRO 4 version but this version completely changed its API making the wrapper obsolete. During the work of porting MDANSE to python 3 I tried to adapt PyRO 3.16 to python 3 but I failed because it triggers changes that became quickly out of control. I also tried to adapt the MDANSE wrapper to PyRO 4 but I gave up for the same reasons. So we are currently stuck. One way to solve this problem would be to use another package to do the SMP parallelization. multiprocessing might be the right candidate because 1) its API is much simpler 2) it is maintained by several persons 3) it is part of the standard distribution. I will investigate on this.

**Comment by RastislavTuranyi** [comment]
It is certainly unfortunate that transition to Pyro4 is difficult, but it is an opportunity to switch to a different package, which I would really support. When I was looking at this some time ago, it seemed that Pyro is far from popular, and there seem to be much better alternatives. It would also allow us, as you said, to drop that entire MasterSlave part of MDANSE code.

In terms of which package, we should definitely investigate the options, since I believe that we want not only to keep current features, but also think about supercomputing etc. Also, I think @sanghamitra-mukhopadhyay mentioned MPI support or something, is that right?

**Comment by eurydice76** [comment]
Yeap indeed. On the other hand through many years of intensive usage at the ILL, there was never a real need for running MDANSE on super computer so I really wonder if we should consider this option first. Moreover, I have strictly no experience at all with MPI but I guess that porting MDANSE to MPI will go for another run of deep refactoring. IMHO, the most important right now is to make the protos branch runnable on SMP machines i.e. machines with multicore.
