### ISSUE TITLE
Protos: serious performance issue when loading a trajectory

### ISSUE THREAD

**Issue by eurydice76** [ISISNeutronMuon/MDANSE#111]
I noticed a quite serious performance issue when loading a trajectory with MDANSE protos. Indeed running that script:

```
from MDANSE.MolecularDynamics.Trajectory import Trajectory
t = Trajectory('./Data/Trajectories/MDANSE/apoferritin.h5')
t.close()
```

takes 5 times longer than its MMTK counterpart:

```
from MMTK.Trajectory import Trajectory
t = Trajectory(None,'./Data/Trajectories/MMTK/apoferritin.nc')
t.close()
```
This has a major impact when running MDANSE on multiprocessors because that overhead is replicated each time we create a instance of the trajectory on a processor. This has the direct consequence that the multiprocessor version is painfully slower than the monoprocessor version !

Now that the release of MDANSE/python2 is almost done. We should both of us focus on this issue because it is of major importance in order to decide if what I wrote can be the future of MDANSE. Given the amount of work I put in this, it is a bit scarry to me but that's the truth.

**Comment by RastislavTuranyi** [comment]
Have you found whether there is any part of the process that causes this slowness, or is it that all parts are slow?

**Comment by eurydice76** [comment]
The slowing part is one the multiprocessing module pickle and unpickle a Job object.

**Comment by RastislavTuranyi** [comment]
Isn't that an issue with the `multiprocessing` module, rather than MDANSE? I.e. that it is slow compared to Pyro?

**Comment by eurydice76** [comment]
yeap because PyRO used a global state approach. With Pyro/MMTK we had the chance to be spoon-fed. If we get rid of Pyro, and I think we should, we have to care about parallelism ourself which is not an easy task.

**Comment by RastislavTuranyi** [comment]
I see, in that case this issue is related to #110, and in fact I think we shouldn't proceed until a decision is made on which module is going to be used, since it will probably be easier to refactor the code only once rather than now to `multiprocessing` and then later to something else if another module is chosen.

In fact, perhaps `multiprocessing` is unsuitable for our purpose, precisely because of the reasons you mentioned; the fact that it needs to pickle/unpickle the entire object every time and because it needs to initialise `Job` in every process?

**Comment by eurydice76** [comment]
On the other hand there is not plenty of choices for multiprocessing with python: multiprocessing or mpi4py. The later also uses pickle mechanism to transfer object.

**Comment by RastislavTuranyi** [comment]
In that case, I can try it out on a small scale and compare the performance against the python2 MDANSE, though it will take a bit since I still have to prepare for the user meeting next week. I will put the results here once finished, unless you would like to try it yourself.

Concerning maintenance, going by the very active GitHub repo and that they are boasting about all the big businesses that use the package, I don't think there's much to worry about.

**Comment by eurydice76** [comment]
OK go ahead. I will also play a bit with Ray on my side. At first sight, it seems quite complicated and I can not avoid the pickle/unpickle to be performed at each step.

**Comment by RastislavTuranyi** [comment]
That's great! I have been looking at Ray, and I got the below results with the current protos commit and the script at the bottom. I don't think there is a way to avoid creating an instance of the Job on every processor/core, but once it's done the results of `run_step()` can be pulled from there. Of course, there's testing to be done on jobs that return from `run_step()` more than just 2 floats to see how efficient the retrieval is, but it doesn't seem terrible at the moment, especially since increasing the cores to 4 decreased the run time to ~5s (btw increasing the Pyro cores to 4 did absolutely nothing).

python2 monoprocessor | python2 multi(3 cores) | python3 monoprocessor | python3 multi(3 cores)
--- | --- | --- | ---
0.5 s | 4.1 s | 4.8 s | 6.2 s

<details><summary>Script that uses Ray</summary><pre><code>
########################################################
This is an automatically generated MDANSE run script #
########################################################

import ray

from MDANSE import REGISTRY

################################################################
Job parameters                                               #
################################################################

parameters = {}
parameters['frames'] = (0, 2257, 1)
parameters['output_files'] = (u'C:\\Users\\dni83241\\Downloads\\NaF_den_new', (u'hdf',))
parameters['running_mode'] = ('monoprocessor',)
parameters['trajectory'] = r'C:\\Users\\dni83241\\Downloads\\NaF.h5'

################################################################
Setup and run the analysis                                   #
################################################################
ray.init()

def run():

    den = REGISTRY['job']['den'].remote()
    den.setup.remote(parameters)
    den.initialize.remote()

    actors = [REGISTRY['job']['den'].remote() for i in range(2)]
    for actor in actors:
        actor.setup.remote(parameters)
        actor.initialize.remote()

    results = []
    for i in range(2257):
        results.append(actors[i % 2].run_step.remote(i))

    for i in range(2257):
        result = ray.get(results[i])
        den.combine.remote(result[0], result[1])

    den.finalize.remote()

import time

start = time.time()
run()
finish = time.time()
print('finished', finish - start)
</code></pre></details>

**Comment by eurydice76** [comment]
Thanks for that work Rastislav. On my side, I explored with multiprocessing module and I could load the trajectory only once per worker which allows to save a lot of time. I did not measure precisely  but it works. What I like with multiprocesing implementation is that it does not change at all the way the job is performed regarding monoprocessor run. You can have a look at the `use_of_multiprocessing_for_smp_parallelization` branch, it contains my work.

**Comment by eurydice76** [comment]
btw, in `use_of_multiprocessing_for_smp_parallelization` branch the code allows to use `multiprocessing` without the need to share the data between workers by using spawning processes. I tried on windows and it seems to work also. So we have a solution that might 1) OS independant 2) use a module that belongs to the standard library 3) scales quite well if you use python code without numpy 4) last but not least avoids to reload the trajectory at every step
