### ISSUE TITLE
Position Autocorrelation Function produces different results in Python 3

### ISSUE THREAD

**Issue by MBartkowiakSTFC** [ISISNeutronMuon/MDANSE#212]
As a part of the ongoing testing of MDANSE code I am running all the possible analysis types using the Python 2 version of MDANSE, and the new Python 3 version. The idea is to run the same analysis with the same parameters on the same trajectory, and check if they produce the same results.

So far I identified that the Position Autocorrelation Function is affected. The results produced by the _protos_ branch are distinctly different from those of the _develop_ branch. 
![pacf](https://github.com/ISISNeutronMuon/MDANSE/assets/108934199/fcbb8f15-8355-45a7-a840-f168e20f7cf7)
Should I assume that the results from the _develop_ branch were correct?

**Comment by ChiCheng45** [comment]
I tested this with another trajectory and get differences between the PACF with the old MDANSE code. It looks like there are some changes to how the coordinates were configured before calculating its correlation. See below.

Protos branch
https://github.com/ISISNeutronMuon/MDANSE/blob/6aeeef700787b13928f910e680dc1b59dc3d04cb/Src/Framework/Jobs/PositionAutoCorrelationFunction.py#L77-L85

Develop branch
https://github.com/ISISNeutronMuon/MDANSE/blob/648affe4fbf90bf55324c2262734ad7ceecf0ce5/Src/Framework/Jobs/PositionAutoCorrelationFunction.py#L75-L84

The develop branch eventually calls MMTK at some point so to work out what its doing differently we need to going digging through that codebase.

Also I'm wondering about how meaningful the current implementation is since It looks like it might depend on the choice of the unit cell since it looks like the PACFs are calculated relative to the origin. It might be better to calculate the PACF using positions relative to its average position over the entire trajectory.

**Comment by MBartkowiakSTFC** [comment]
I would expect that the correct calculation of PACF should be unaffected by an arbitrary translation of the entire trajectory by a vector. If you agree with this, you could probably add a unit test for it.

To add complexity to it, MDANSE will handle differently the systems with and without periodic boundary conditions. So, we would need a few different inputs for testing.

**Comment by ChiCheng45** [comment]
I've tried adjusting the way the PACF is calculated by calculating the positions relative to the average position over the entire trajectory. The results appear more reasonable than either MDANSE versions to me and I think we should change it. For the trajectory you used above I get this.

![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/dbdb558c-a203-4983-a8d0-ef16146fcbaa)

The previous version calculated the PACF with something like this

$$\mathrm{PACF}(t) = \frac{1}{N} \sum_{i}^{N} \langle R_{i}(0) \cdot R_{i}(t)\rangle$$

We can see that this PACF will depend on the origin of the coordinate system since if we translate the system $R_{i} \rightarrow R_{i} + T$ the PACF will change. In the adjusted version I've change it to

$$\mathrm{PACF}(t) = \frac{1}{N} \sum_{i}^{N} \langle \Delta R_{i}(0) \cdot \Delta R_{i}(t)\rangle$$

where $\Delta R_{i}(t) = R_{i}(t) - R_{\mathrm{avg}}$ and $R_{\mathrm{avg}}$ is the average position of atom $i$ across the entire trajectory. This is similar to the positional autocorrelation function equation in the last paragraph of section 3 in https://doi.org/10.1143/PTPS.178.86.
