### ISSUE TITLE
[BUG] Unusual RDF result in pair distribution function job.

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#431]
**Description of the error**
According to the documentation (https://mdanse.readthedocs.io/en/protos/pages/structure.html#pair-distribution-function), the pair distribution function job also calculates the radial distribution function. I ran the pair distribution function job with a water trajectory (which is periodic) but the RDF it produces does not look like a typical RDF from the literature. Some weird thing about the MDANSE RDF include the fact that it goes to zero as R get large which is wrong.

**Additional details**
Generated using the DFTB  water trajectory.

![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/6f672996-d5d0-4baf-8cca-e12b6eded5c8)

vs. for example fig.5 from this paper https://arxiv.org/pdf/2312.15211.

![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/bcb5620e-db92-4582-95ed-7ea57a0f26a1)

**Comment by gonzalezma** [comment]
Note that the paper figure that you show displays the pair-distribution function (PDF) g(r). The PDF output of MDANSE should show something similar. The radial distribution function (RDF) is defined as 4*pi*r**2*rho*g(r), so it grows with r as r**2. And the decay to zero could be because r becomes > L/2, so one cannot compute g(r) correctly any more? If you are interested in the different PDF, RDF and D(r) definitions, check pp. 245-248 in doi:10.1088/0034-4885/69/1/R05
