### ISSUE TITLE
[BUG] How important is the imaginary part of F(q, t)?

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#466]
The correlate function in MDANSE always returns the real part. Additionally in the Fourier transform code it applies a symmetrization to F(q, t) prior to applying the FFT this means that it assumes that F(q, t) = F(q, -t) which is valid if F(q, t) is real (which it is since we dropped the imaginary part in the correlate function).

However, we know that actually F(q, t) = F*(q, -t). How important is the imaginary part and is it always small?

**Comment by gonzalezma** [comment]
This is an interesting, but difficult question to answer. We assume that the classical interpretation of the correlation function given by Van Hove is valid, so that F(Q,t) is real and even, and therefore S(Q,f) as well. From the experimental point of view this is known to be false, as S(Q,f) must obey the detail balance relation and some sum-rules that are not respected by a real and even S(Q,f). But to my knowledge, there is no simple way of doing anything better. On the positive side, if the energies are low enough, the classical view is a reasonable approximation. This will break if we look to inelastic excitations, in particular intramolecular vibrations, but in this case one can also question how reliably can be those computed using a classical simulation. If you are interested in the problem, you can check these references:
Evans and Ojeda, J. Mol. Liq. 54, 321 (1992)
Kneller, Mol. Phys. 83, 63 (1994)
But I do not see any practical way of implementing any of that in MDANSE.

**Comment by ChiCheng45** [comment]
Closing, we can come back to this again if it is important.
