### ISSUE TITLE
ENHANCEMENT: Create more granular plotting options for trajectory variables

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#58]
Currently, the plotting of variables in MMTK NetCDF trajectories is far from useful, as documented in #34. All the variables in these trajectories do not have the 'Axis' parameter, which determines what the data is plotted against. Many of these variable also do not provide any meaningful information (e.g. the plot of time against time etc.). Yet others are, however, so packed with information as to be indecipherable. This latter category includes configuration, velocities, and gradients. The 3D plot which plots all the x,y,z components for every atom at every time-step into one graph is too dense to be useful. However, parts of this dataset contain very valuable information.

Therefore, the plotting options for MMTK NetCDF trajectories should be greatly expanded. This should include the following options and possibly more:

- plot the components of coordinates/velocities/gradients of particular atoms against time
- plot coordinates/velocities/gradients of particular atoms against time

All of this has arisen from the discussions in #34, but if anyone has further ideas for what would be good to be able to be plotted, please share!

**Comment by eurydice76** [comment]
I agree that the current plotting of variables such as coordinates, velocities or gradients are not really useful. However, it should be kept in mind that the plotter of MDANSE was designed to be the most generic as possible. As such, it can be considered as a NetCDF file plotter. In that context, there is no "intelligence" in plotting the variables in the sense that e.g. coordinates will be considered as a 3D variable and so the plotter will propose to plot them using appropriate plotter (i.e. 3D). Making the plotter MD compliant with the plotting of MD variables such as coordinates, velocities or gradients being treated differenly than the other variables 1) breaks the generality of the plotter which is a pity 2) would need a deep rewriting of the plotter - good luck !

**Comment by eurydice76** [comment]
I pushed a new [branch](https://github.com/ISISNeutronMuon/MDANSE/tree/58_md_compliant_plotter) which solves in some way the problem. Basically I added a new mode for plotting 3D data called 2D slice. For any 3D data, its plots a 2D image for a selected dim and a slice along that dimension. From there, we can use the already implemented slice mode which allows to have 1D slice plots which would correspond to what @sanghamitra-mukhopadhyay would like to have. For example, say that we want to plot the velocities against time for the first atom then we would select dim = 1 and slice = 0 (the velocities array has dimension (nFrames,nAtoms,3)) and from there do a slice plot.
This solution yet not perfect has some advantages: 1) it does not break the generality of our plotter 2) it uses already coded material. It seems to me a good compromise otherwise that means that we would have to rewrite deeply the plotter and as I said good luck ! We also have to think that inspecting those values (coords, velocities or gradients) are quite unusual. We could live for 10 years at the ILL without really having the need for this unless for inspected buggy trajectories. So is it worth rewriting such an important part of the code for that ? The question is raised.

**Comment by eurydice76** [comment]
I pushed a new commit on the branch 58. It implements a brand new ComponentPlugin specifically dedicated to the viewing of Trajectory variables (the ones of dim nframes x natoms x 3). It is accessible under the Miscellaneous section under the Molecular Viewer plugin. As such, once a variable and a dimension selected, you can pick up an atom from the viewer and it corresponding variable will be plotted. It should fulfill directly the need of @sanghamitra-mukhopadhyay. Any suggestion are welcome.
