### ISSUE TITLE
ENHANCEMENT: Add abstraction for plotter data

### ISSUE THREAD

**Issue by eurydice76** [ISISNeutronMuon/MDANSE#68]
Quite soon, we will have to deal with hdf5 file in MDANSE. However, it would be good if the plotter could handle both NetCDF and HDF files transparently. To do so we have to add a layer of abstraction around the data passed to the plotter.

**Comment by eurydice76** [comment]
Hi @RastislavTuranyi , I made some advances in the plotter data abstraction. It is nearly finished. As the reminder, the goal is to provide an abstraction layer to give to the plotter the possibility to accept both NetCDF and HDF (and why not other formats in the future) file in a nice way. Everything seems OK and we are in position to have a plotter for any NetCDF file (even ones not coming from MDANSE) now but at one cost. Indeed, thanks to the new NetCDF4 dependency, we can now have nested variables in the NetCDF file hierarchy. This was not possible with the implementation in Scientific.IO.NetCDFFile. This is a cool feature. So that means that we have to recursively find all the variables present in the hierarchy starting from '/'. So every variable found will have a name like '/msd', '/time' ... This is how it will be displayed in the plotter. I am OK with this because this name reflects where the variables is located in the file hierarchy and as such it provides some information. But on the other hand I can understand that you or MDANSE user may find this less lice than before where the variable was displayed without '/' at the beginning. Could you please give a try and tell me what you think of this ?

**Comment by RastislavTuranyi** [comment]
I think that having the / show in the variable box is not a huge issue, but when it appears in a plot, the user will have to manually edit it out every time they want to use the plot. Further, I think it has a potential to cause confusion as to what is going on in the plot, since not everyone would be able to associate the / with file structure (I wouldn't realise if you hadn't told me), as opposed to e.g. division or something like that. Overall, I think what a user wants from an MDANSE plot, is a standard plot that can be used in other context, and a / before a variable name is not part of a standard plot.

Regardless, isn't it easy to remove the / from the plot? E.g. instead of `self.Xaxis_label = self.dataproxy[varname]['axis'][0]` do `self.Xaxis_label = self.dataproxy[varname]['axis'][0].replace('/', '')`.

**Comment by eurydice76** [comment]
Yeap I was thinking about a code like so but what if the NetCDF file contains nested variables such as `/toto/titi/var`. We will endup with a variable label set to `toto/titi/var`. Hum, not nice too. Or we could think about flattening the file hierarchy such that for instance `toto/titi/var` ends up with `var`. In case where two nested variables has the same variable name for instance `/toto/titi/var` and `/tete/var` we name the first one `var` and the second one `var_1`.

**Comment by eurydice76** [comment]
I think that I came up with a good compromise in my last commit. The variable are now flattened with a special care of duplicates. For each variable I also store the path they have in the NetCDF file like so the user can see which one is which in case of duplicate. This appears in an extra column named `Path` in the datalist list widget. What do you think ?
