### ISSUE TITLE
ENHANCEMENT: Create a way to transform S(Q, ω) into S(Q, E)

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#75]
In my discussions at NMSUM, one of the issues that was expressed to me is that often the scattering function S is of greater interest as a function of energy rather than of frequency. This is not a major problem, but it does add a layer of difficulty to data interpretation, and so removing this would be a nice quality-of-life change. 

There are two ways in which I think this could be achieved:

- Change the DSF analyses to create new outputs, or
- Add a feature to the 2D/3D Plotter that allows for not only unit conversion, but also a limited physical quantity conversion.

**Comment by gonzalezma** [comment]
There is already a unit converter in the 2D/3D plotter. Personally, I don't find it too useful, but I don't understand what you mean by physical quantity conversion. I imagine that you mean e.g. rad/ps vs meV vs cm-1 vs THz, although I would call this simply unit conversion. I thought that the unit converter was able to do this, but I could not manage to make it work myself (I get an error message the the axis unit is inconsistent with the current unit).

The unit converter affects only to the plot and not to the netCDF file, so this is not very useful if one wants to compare the MD result to experiment, which I assume is done outside MDANSE. The alternative is to add an option to each relevant analysis allowing to choose the output units, which is something that was already possible in some nMoldyn versions. Personally, I prefer the new way, but I admit that this is debatable. My reasons are:

1. This removes one option from the analysis menu. And simplifies the analysis, which otherwise needs to include a unit conversion at the end.

2. It is clearer that after converting a trajectory, all internal handling and analysis outputs are in MDANSE units (basically nm, 1/nm, ps, rad/ps). Then converting to any other unit is straightforward and should not be a problem for any user.

So I prefer to keep the code and input menu simpler at the cost of making life perhaps a little bit more uncomfortable to the users. I would even add that there is some educational value in understanding the relationship between the different units and how to pass from one to another, and that anyone trying to compare MD and experiment should be able to handle this and not use MDANSE blindly.

But if we decide to make user's life easier, I would go for the option of selecting the units in the input of the analysis. We should decide then to which analysis and quantities to apply it (only for the frequency/energy or also for time, length, wavevector, etc.) and how generous we should be with the units (e.g. only angstrom and nm for length, or also cm, mm, m, etc.).

**Comment by eurydice76** [comment]
I agree with Miguel. I do think that we should keep an internal consistency and propose a better conversion at the plotter level. I will rewrite the Units converter so thqt it can process so-called equivalent units (e.g: eV <--> THz).

**Comment by sanghamitra-mukhopadhyay** [comment]
The default unit of E or Q varies instruments to instruments, so it is better to keep this option as a choice for users. This can be applied both on plotters and so to the output options, if users choose to take the output as a datafile to plot themselves on external commercial applications, such as Origin. These conversions are already implemented on Mantid, so we can take that from there.

**Comment by eurydice76** [comment]
Hi @sanghamitra-mukhopadhyay @gonzalezma @RastislavTuranyi, I just pushed on branch [75](https://github.com/ISISNeutronMuon/MDANSE/tree/75_units_manager) some significative improvments concerning the units. Indeed, it is now possible to perform a unit conversion for so-called equivalent units (e.g. THz/eV, THz/K ...). The plotter is now aware of these changes. To use them you should have to change the Units of an axis in the settings and the conversion will be perform automagically. Rastislslav, to make it work the package `pyyaml` should be installed on the build machine. I also implemented an application for editing units (add/delete/modify). The app has to be completed. With the new units and that tool at hand we can keep on working with or internal units like before as (rightly) suggested by Miguel. Please try and give me feedback.

**Comment by RastislavTuranyi** [comment]
Thank you! I am going to take a look, but can you please open a PR? It's easier to view and discuss code changes on a PR than in an issue.
