### ISSUE TITLE
investigation: python2 to python3 requirements

### ISSUE THREAD

**Issue by franzlang** [ISISNeutronMuon/MDANSE#9]
As of 1st January 2020 Python 2 is no longer officially supported: https://www.python.org/doc/sunset-python-2/
However, the current code is Python 2. Investigate and document what parts of the code and its dependencies have to be changed/updated/replaced to enable the code to transferred to Python 3.
Create corresponding issues for all parts of the code and any dependencies that need to be updated.

**Comment by sanghamitra-mukhopadhyay** [comment]
Dependencies on MMTk is the main point of using python 2. About 15% of the MMTk code is used in MDANSE, particularly for working with trajectories. The use of other codes, such as Mosaic and MDAnalysis have been explored, see issue #12 and #13. Converting/rewriting parts, which are using MMTk seems best solutions, rather than using the above mentioned codes. since all need some reworking.  Rest of the code without MMTk is written in Python 3. See issue #2.
