### ISSUE TITLE
BUG: reading XTD file in MaterialsStudio leads to wrong AtomCluster

### ISSUE THREAD

**Issue by eurydice76** [ISISNeutronMuon/MDANSE#95]
A bug was found in the MaterialsStudio based converters (Forcite, Discover). Indeed, when parsing the XTD file, the underlying atom clusters are not reconstructed properly. I will investigate on this.

**Comment by eurydice76** [comment]
Hi @RastislavTuranyi , it seems that the build server behaves badly. Indeed, I pushed on branch 95 to fix a bug with the Forcite converter. To improve the converter, I added a configuration option called `fold`. When the build server performs the unit tests two problems appear. The first one is the fact that the `TestForcite` fails complaining about the fact that `fold` is missing from the configuration which should not happen. The second one is that the tests is succeeding on macos but failing on linux and windows which should not happen too. Could you please investigate on this ?

**Comment by RastislavTuranyi** [comment]
You might have noticed, but your branch was created from an older commit, before the patch to MacOS CI was merged, and that's why it was succeeding. Now that you have merged develop, it is failing as it should.

Concerning the failing tests, the DFTB test fails on my laptop too, so I don't think it's an issue with the CI. Is this tests succeeding when you run it on your computer?

**Comment by RastislavTuranyi** [comment]
I think the DFTB test fails because the `DFTBConverter` class overwrites the `settings` dict without including the `fold` parameter.

**Comment by eurydice76** [comment]
Thanks for the hint, I will check

**Comment by eurydice76** [comment]
Hi Rastislav, it has been fixed in the protos branch but not yet in the develop branch. I will do this.
